#!/bin/bash

VERSION=2.028

umask 022

TOP=$PWD
BIN=$TOP/bin

TMP="${TMPDIR:-/tmp}/MailBox"

HTML="${TMPDIR:-/tmp}/MailBox-html"
HTMLOUT="$HTML-output"
HTMLERR="$HTML-errors"
SITE=/home/markov/shared/perl/public_html/mailbox

open_up()
{   DIR="$1"
    echo "opening $DIR"
    [ -d $DIR ] || exit $?

    find $DIR         -exec chmod a+r {} \;
    find $DIR -type d -exec chmod a+x {} \;
}


echo ">>> Producing version $VERSION"
[ -d "$TMP/tests" ]   || mkdir "$TMP/tests";

echo ">>> Create pod"
$BIN/make_pod $TMP $VERSION || exit $?

cd $TMP               || exit $?
find Mail -name \*.pod >>MANIFEST
sort -u MANIFEST >x && mv x MANIFEST

echo ">>> Run tests"
perl Makefile.PL      || exit $?
chmod a+x test.pl tests/*/*.t
make test             || exit $?

echo ">>> Creating HTML with mpod2html"
rm -rf $HTML
find Mail -name \*.pod | cpio -pduma $HTML
cp pod.css $HTML      || exit $?

cp method-index $HTML || exit $?
cd $HTML              || exit $?

mpod2html . >$HTMLOUT 2>&1 || exit $?

sed <$HTMLOUT >$HTMLERR '
  /^\+\+\+/d
  /^Writing /d
  /syntax OK/d
  /^[ \\t]*$/d
  '

if [ -s $HTMLERR ]
then echo "HTML errors:"
     cat $HTMLERR
fi

echo ">>> Improving HTML with make_html"

for h in `find Mail -name \*.html`
do
    $BIN/improve_html method-index $h >x && mv x $h
done

echo ">>> Creating a nicer index"

$BIN/make_podindex method-index >podindex.html

rm method-index

echo -n "Continue with distribution? [n/y] "
read CONT
case "$CONT" in
y*) ;;
*)  echo ">>> No distribution created"
    exit 0;;
esac

echo ">>> HTML to website"

cd $HTML
rm -rf $SITE/html
mkdir $SITE/html

tar -cf $SITE/html/html-current.tar *
gzip -9f $SITE/html/html-current.tar
(cd $SITE/html; ls -lh html-current.tar.gz)

cp -r * $SITE/html
open_up  $SITE/html

echo ">>> Make dist"
cd $TMP
DIST=Mail-Box-$VERSION.tar.gz
rm -f $DIST
make dist >/dev/null

(cd $TMP; ls -lh $DIST)

[ -d $SITE/source ] || mkdir $SITE/source
cp $TMP/$DIST $SITE/source/
ln -sf $DIST $SITE/source/source-current.tar.gz
open_up $SITE/source

INDEX=$SITE/source/index.html
echo >$INDEX <<'page_head'
<HTML>
<HEAD><TITLE>Older sources of Mail::Box</TITLE></HEAD>
<BODY BGCOLOR=white>
page_head

for f in $(cd $SITE/source; ls *gz)
do echo "<A HREF=\"$f\">$f</A><BR>" >>$INDEX
done

echo >>$INDEX <<'page_tail'
</BODY></HTML>
page_tail

echo ">>> Make raw"

cd $TOP
[ -d $SITE/raw ] || mkdir $SITE/raw
RAW=Mail-Box-raw.$VERSION.cpio
cat MANIFEST MANIFEST.raw | cpio -oca >$SITE/raw/$RAW
bzip2 -9f $SITE/raw/$RAW
ln -sf $RAW.bz2 $SITE/raw/raw-current.cpio.bz2
(cd $SITE/raw; ls -lh $RAW.bz2)
open_up $SITE/raw

echo ">>> Ready"
