#!/bin/bash

echo "Checking";
for f in `grep '^Mail/.*\.pm$' MANIFEST`
do  echo "$f: checking"
    perl -I. -e "require '$f'"
done

for f in `grep '^Mail/.*\.pm$' MANIFEST`
do  echo "$f: updating";
    ./update_one_index $f $f.new && mv $f.new $f
done
